# Generated by Django 3.1.2 on 2020-10-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('squirrel_id', models.SlugField(max_length=14, primary_key=True, serialize=False)),
                ('hectare', models.CharField(default='', max_length=4)),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=3)),
                ('date', models.CharField(default='', max_length=9)),
                ('hectare_sq', models.IntegerField(default=0)),
                ('age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('', '')], default='', max_length=20)),
                ('primary_fur', models.CharField(default='', help_text='Primary Fur Color', max_length=20)),
                ('highlight_fur', models.CharField(blank=True, default='', help_text='Highlight Fur Color', max_length=20)),
                ('combi_fur', models.CharField(blank=True, default='', help_text='Combine Fur Color', max_length=40)),
                ('color_note', models.CharField(blank=True, default='', help_text='Color Note', max_length=40)),
                ('location', models.CharField(choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane'), ('', '')], default='', help_text='Locations', max_length=20)),
                ('above_ground', models.CharField(blank=True, default='', help_text='How Far from Ground Please Put The Number. If Found On The Ground Please Put FALSE', max_length=20)),
                ('spec_loc', models.CharField(blank=True, default='', help_text='Specific Location', max_length=70)),
                ('running', models.BooleanField(default=True)),
                ('chasing', models.BooleanField(default=True)),
                ('climbing', models.BooleanField(default=True)),
                ('eating', models.BooleanField(default=True)),
                ('foraging', models.BooleanField(default=True)),
                ('other_act', models.CharField(blank=True, default='', help_text='Report any other activities and leave it empty if there is none', max_length=30)),
                ('kuks', models.BooleanField(default=True)),
                ('quaas', models.BooleanField(default=True)),
                ('moans', models.BooleanField(default=True)),
                ('flags', models.BooleanField(default=True)),
                ('twitches', models.BooleanField(default=True)),
                ('approaches', models.BooleanField(default=True)),
                ('indifferent', models.BooleanField(default=True)),
                ('runsfrom', models.BooleanField(default=True)),
                ('other_int', models.CharField(blank=True, default='', help_text='Report any other interaction and leave it empty if there is none', max_length=30)),
                ('lat_long', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
    ]
