# Generated by Django 3.1.2 on 2020-10-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField(help_text='Latitude')),
                ('Longitude', models.FloatField(help_text='Longitude')),
                ('Unique_Squirrel_ID', models.CharField(help_text='The Unique ID', max_length=14)),
                ('Hectare', models.CharField(blank=True, help_text='Hectare', max_length=4)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=3)),
                ('Date', models.CharField(help_text='Date', max_length=9)),
                ('Hectare_squirrel_nunber', models.IntegerField(blank=True, help_text='Hectare Number')),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('', '')], default='', help_text='Age', max_length=20)),
                ('Primary_Fur_Color', models.CharField(blank=True, help_text='Primary Fur Color', max_length=20)),
                ('Highlight_Fur_Color', models.CharField(blank=True, help_text='Highlight Fur Color', max_length=20)),
                ('Combi_Fur_Color', models.CharField(blank=True, help_text='Combine Fur Color', max_length=40)),
                ('Color_Notes', models.CharField(blank=True, help_text='Color Note', max_length=40)),
                ('Location', models.CharField(choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane'), ('', '')], default='', help_text='Locations', max_length=20)),
                ('Above_Ground', models.CharField(blank=True, help_text='How Far from Ground Please Put The Number. If Found On The Ground Please Put FALSE', max_length=20)),
                ('Specific_Location', models.TextField(blank=True, help_text='Specific Location')),
                ('Running', models.BooleanField()),
                ('Chasing', models.BooleanField()),
                ('Climbing', models.BooleanField()),
                ('Eating', models.BooleanField()),
                ('Foraging', models.BooleanField()),
                ('Other_Activ', models.TextField(blank=True, help_text='Other Activites')),
                ('Kuks', models.BooleanField()),
                ('Quaas', models.BooleanField()),
                ('Moans', models.BooleanField()),
                ('Tail_flags', models.BooleanField()),
                ('Tail_twitch', models.BooleanField()),
                ('Approaches', models.BooleanField()),
                ('Indifferent', models.BooleanField()),
                ('Runs_from', models.BooleanField()),
                ('Other_Inter', models.CharField(blank=True, help_text='Other Interactions', max_length=20)),
                ('Lat_Long', models.CharField(max_length=100)),
            ],
        ),
    ]
