# Generated by Django 3.1.2 on 2020-10-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default='0.00')),
                ('y', models.FloatField(default='0.00')),
                ('unique_squirrel_id', models.CharField(default='', max_length=14)),
                ('hectare', models.CharField(blank=True, default='', help_text='Hectare', max_length=4)),
                ('shift', models.CharField(default='', max_length=3)),
                ('date', models.CharField(default='', help_text='Date', max_length=9)),
                ('hectare_sq', models.IntegerField(default=0, help_text='Hectare Number')),
                ('age', models.CharField(default='', help_text='Age', max_length=20)),
                ('primary_fur', models.CharField(blank=True, default='', help_text='Primary Fur Color', max_length=20)),
                ('highlight_fur', models.CharField(blank=True, default='', help_text='Highlight Fur Color', max_length=20)),
                ('combi_fur', models.CharField(blank=True, default='', help_text='Combine Fur Color', max_length=40)),
                ('color_note', models.CharField(blank=True, default='', help_text='Color Note', max_length=40)),
                ('location', models.CharField(default='', help_text='Locations', max_length=20)),
                ('above_ground', models.CharField(default='', max_length=20)),
                ('spec_loc', models.CharField(default='', max_length=70)),
                ('running', models.BooleanField()),
                ('chasing', models.BooleanField()),
                ('climbing', models.BooleanField()),
                ('eating', models.BooleanField()),
                ('foraging', models.BooleanField()),
                ('other_act', models.CharField(default='', max_length=30)),
                ('kuks', models.BooleanField()),
                ('quaas', models.BooleanField()),
                ('moans', models.BooleanField()),
                ('flags', models.BooleanField()),
                ('twitches', models.BooleanField()),
                ('approaches', models.BooleanField()),
                ('indifferent', models.BooleanField()),
                ('runsfrom', models.BooleanField()),
                ('other_int', models.CharField(blank=True, default='', max_length=20)),
                ('lat_long', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
