# Generated by Django 3.1.2 on 2020-10-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquirrelTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('unique_squirrel_id', models.CharField(max_length=14)),
            ],
        ),
    ]
