# Generated by Django 3.1.2 on 2020-10-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='Approaches',
            new_name='approaches',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Chasing',
            new_name='chasing',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Climbing',
            new_name='climbing',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Eating',
            new_name='eating',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Foraging',
            new_name='flags',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Indifferent',
            new_name='foraging',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Kuks',
            new_name='indifferent',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Moans',
            new_name='kuks',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Quaas',
            new_name='moans',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Running',
            new_name='quaas',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Runs_from',
            new_name='running',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Tail_flags',
            new_name='runsfrom',
        ),
        migrations.RenameField(
            model_name='squirrel',
            old_name='Tail_twitch',
            new_name='twitches',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Above_Ground',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Color_Notes',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Combi_Fur_Color',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Hectare',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Hectare_squirrel_nunber',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Highlight_Fur_Color',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Lat_Long',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Longitude',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Other_Activ',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Other_Inter',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Primary_Fur_Color',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Shift',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Specific_Location',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='Unique_Squirrel_ID',
        ),
        migrations.AddField(
            model_name='squirrel',
            name='above_ground',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='age',
            field=models.CharField(default='', help_text='Age', max_length=20),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='color_note',
            field=models.CharField(blank=True, default='', help_text='Color Note', max_length=40),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='combi_fur',
            field=models.CharField(blank=True, default='', help_text='Combine Fur Color', max_length=40),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='hectare',
            field=models.CharField(blank=True, default='', help_text='Hectare', max_length=4),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='hectare_sq',
            field=models.IntegerField(default=0, help_text='Hectare Number'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='highlight_fur_Color',
            field=models.CharField(blank=True, default='', help_text='Highlight Fur Color', max_length=20),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='lat_long',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='location',
            field=models.CharField(default='', help_text='Locations', max_length=20),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='other_act',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='other_int',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='primary_fur_Color',
            field=models.CharField(blank=True, default='', help_text='Primary Fur Color', max_length=20),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='shift',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='specific_loc',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='unique_squirrel_id',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='x',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='y',
            field=models.FloatField(default='0.00'),
        ),
    ]
