# Generated by Django 3.1.2 on 2020-10-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Lat_Long',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Unique_Squirrel_ID',
            field=models.SlugField(help_text='The Unique ID', max_length=14, primary_key=True, serialize=False),
        ),
    ]
