# Generated by Django 3.1.2 on 2020-10-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0002_auto_20201017_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='date',
            field=models.CharField(default='', help_text='Date', max_length=9),
        ),
    ]
