# Generated by Django 3.1.2 on 2020-10-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0004_auto_20201018_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirreltest',
            name='chasing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='squirreltest',
            name='climbing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='squirreltest',
            name='eating',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='squirreltest',
            name='foraging',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='squirreltest',
            name='running',
            field=models.BooleanField(default=True),
        ),
    ]
