# Generated by Django 3.1.2 on 2020-10-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0005_auto_20201018_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirreltest',
            name='approaches',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='squirreltest',
            name='flags',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='squirreltest',
            name='indifferent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='squirreltest',
            name='kuks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='squirreltest',
            name='lat_long',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='squirreltest',
            name='moans',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='squirreltest',
            name='other_act',
            field=models.CharField(blank=True, default='', help_text='Report any other activities and leave it empty if there is none', max_length=30),
        ),
        migrations.AddField(
            model_name='squirreltest',
            name='other_int',
            field=models.CharField(blank=True, default='', help_text='Report any other interaction and leave it empty if there is none', max_length=30),
        ),
        migrations.AddField(
            model_name='squirreltest',
            name='quaas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='squirreltest',
            name='runsfrom',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='squirreltest',
            name='twitches',
            field=models.BooleanField(default=True),
        ),
    ]
