# Generated by Django 3.1.2 on 2020-10-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0006_auto_20201018_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Squirrel',
        ),
    ]
